services:
  app:
    build:
      context: .
      dockerfile: .build/dockerfiles/Dockerfile
      target: dev
    volumes:
      - "./app:/app:cached"
      - "./.data/bob-s-home:/home/bob:cached"
    environment:
      - APP_NAME=zcs-python-core
      - TERM=xterm-256color
      - TZ=Europe/Rome