[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "zcs-python-core"
version = "0.3.0"
description = "A Python library that provides core functionalities for ZCS projects"

[tool.setuptools.packages.find]
where = ["./src"]
